### ISSUE TITLE
CA05 - En tant qu'utilisateur de la suite applicative mobile, je dois pouvoir s'authentifier une seule fois  grâce à mon compte du réseau social et conserver les informations de connexion par la suite

### ISSUE THREAD

**Issue by fbonilla** [gti525/h18-mobile-social#36]

**Comment by fbonilla** [comment]
Utiliser le local storage déja présent dans le projet.

**Comment by hp90** [comment]
L'utilisateur peut maintenant recouvrir l'application et l'application essayera de le re authentifier automatiquement à l'API de Unik grâce au Local Storage.

Pour qu'un utilisateur ne se reconnecte pas automatiquement, il doit clicker sur "Déconnexion" dans le Menu.
