### ISSUE TITLE
CB23 - En tant que développeur, je dois ajuster le flow de navigation de l'application

### ISSUE THREAD

**Issue by fbonilla** [gti525/h18-mobile-social#37]
- Contrôler l'action du back button
- Ajout du flow pour la déconnexion
- Retour sur la page d'acceuil apres le paiement

**Comment by hp90** [comment]
Fonction complété:
1) Navigation:
  1.1) Navigation dans le side menu
  1.2) Navigation des pages
Fonction à ajouté:
1) Lorsqu'un utilisateur se déconnecte, l'utilisateur est redirigé à la page Login.
2) Lorsqu'un utilisateur se déconnecte, nous devons effacer le Local Storage
3) Lorsqu'un utilisateur vient de payer pour la version Premium, il est remercié et dirigé vers la page d'accueil (présentement intitulé À Venir).
4) Lorsqu'un utilisateur à déjà payer pour la version Premium, il ne peut plus repayer pour celle-ci
