### ISSUE TITLE
CB04 - En tant qu'application de billet électronique, je dois être en mesure de conserver en mémoire la liste des billets que je possède afin d'avoir accès aux spectacles malgrés l'absence d'une connectivité à internet

### ISSUE THREAD

**Issue by fbonilla** [gti525/h18-mobile-social#47]

**Comment by fbonilla** [comment]
local storage gg no re.

**Comment by hp90** [comment]
1. Check if Internet is available
1. 1. Internet is available
1. 1. 1. Do what we do now
1. 2. Internet is not available
1. 2. 1. Alert the user: "You are in Offline Mode - Only Tickets are accessible"
1. 2. 2. Access the account (No login required)
