### ISSUE TITLE
CB13 - En tant que développeur, je dois faire un diagramme des cas d'utilisations

### ISSUE THREAD

**Issue by fbonilla** [gti525/h18-mobile-social#5]
En parallèle avec l'analyse des requis et exigences, il sera possible de produire ce premier artéfact.

**Comment by fbonilla** [comment]
- Lister les cas d'utilisations
- Les inclure dans un DCU avec les acteurs impliqués

**Comment by hp90** [comment]
J'ai fait un document de cas d'utilisation en me basant sur ton diagramme.
Ce document se trouve dans le Google Drive (Documentation/Modèle du Domaine).
Seuls les cas où l'utilisateur qui utilisent l'application Mobile Social sont élaborés.
