### ISSUE TITLE
CA05-En tant qu'utilisateur de la suite applicative mobile je dois pouvoir s'authentifier une seule fois  grâce à mon compte du réseau social et conserver les informations de connexion par la suite

### ISSUE THREAD

**Issue by MaxenceVacher1** [gti525/h18-mobile-social#62]
En tant qu'utilisateur de la suite applicative mobile je dois pouvoir s'authentifier une seule fois  grâce à mon compte du réseau social et conserver les informations de connexion par la suite

**Comment by hp90** [comment]
Le premier des 2 issue (CA05) est complété. PR a été créé.
Si vous voulez testé, vous devez le faire avec un device (peut-être l'émulateur Android fonctionnerait)
